version: '3.4'

services:
    mssql-db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"  
    postgres-db:
        image: "postgres"
        environment:
            POSTGRES_USER: "my_user"
            POSTGRES_PASSWORD: "my_pw"  
    integration-tests-mssql:
        image: ${DOCKER_REGISTRY-}webapisample-integrationtests
        build:
          context: .
          target: integrationtestrunner
          dockerfile: CoreHost/Dockerfile
        environment:
          - "DatabaseType=mssql"
          - "ConnectionStrings__Cinematic_mssql=Server=mssql-db;Database=Cinematic_Tests;User=sa;Password=Your_password123;"
        volumes:
        - "./docker-test-results:/src/Api.IntegrationTests/TestResults"
            
        depends_on:
            - mssql-db
    integration-tests-postgres:
        image: ${DOCKER_REGISTRY-}webapisample-integrationtests
        build:
          context: .
          target: integrationtestrunner
          dockerfile: CoreHost/Dockerfile
        environment:
          - "DatabaseType=postgres"
          - "ConnectionStrings__Cinematic_postgres=Host=postgres-db;Database=Cinematic_Tests;Username=my_user;Password=my_pw;"
        volumes:
        - "./docker-test-results:/src/Api.IntegrationTests/TestResults"
            
        depends_on:
            - postgres-db
