version: '3.4'

services:
    webapisample:
        image: ${DOCKER_REGISTRY-}webapisample
        build:
          context: .
          dockerfile: CoreHost/Dockerfile
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"  
