version: '3.4'

services:
  corehost:
    image: ${DOCKER_REGISTRY-}corehost
    build:
      context: .
      dockerfile: CoreHost/Dockerfile
    depends_on:
    - postgres-db

  postgres-db:
    image: "postgres"
    environment:
        POSTGRES_USER: "my_user"
        POSTGRES_PASSWORD: "my_pw"
