version: '3.4'

services:
  corehost:
    image: ${DOCKER_REGISTRY-}webapisample:${BUILDNUMBER-dev}
    build:
      context: .
      dockerfile: CoreHost/Dockerfile
      args:
        RUNTIME_VERSION: "${RUNTIME_VERSION-5.0-buster-slim}" #"5.0-buster-slim-arm32v7"
    depends_on:
    - postgres-db

  postgres-db:
    image: "postgres"
    environment:
        POSTGRES_USER: "my_user"
        POSTGRES_PASSWORD: "my_pw"
    ports:
    - 5432:5432
