Vagrant.configure("2") do |config|

    config.vm.define "web" do |web|
        web.vm.box = "gusztavvargadr/w16s-iis"

        web.vm.provider "hyperv" do |h|
            h.vmname = "dnz-webapi-w16s-iis"
            h.memory = 1024
            h.differencing_disk = true
            h.vm_integration_services = {
                guest_service_interface: true,
                heartbeat: true,
                key_value_pair_exchange: true,
                shutdown: true,
                time_synchronization: true,
                vss: true
            }
          end  
    end

    config.vm.define "db" do |db|
        db.vm.box = "gusztavvargadr/w16s-sql17d"
        db.vm.box_version = "0.8.0"
    
        db.vm.provider "hyperv" do |h|
            h.vmname = "dnz-webapi-w16s-sql17d"
            h.memory = 2048
            h.differencing_disk = true
            h.vm_integration_services = {
                guest_service_interface: true,
                heartbeat: true,
                key_value_pair_exchange: true,
                shutdown: true,
                time_synchronization: true,
                vss: true
            }
        end
    end

  
end
  