Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/u16"
    config.vm.box_version = "0.1.0"

    config.vm.provider "hyperv" do |h|
        h.vmname = "dnz-webapi-ubuntu"
        h.memory = 1024
        h.differencing_disk = true
        h.vm_integration_services = {
            guest_service_interface: true,
            heartbeat: true,
            key_value_pair_exchange: true,
            shutdown: true,
            time_synchronization: true,
            vss: true
        }
    end  

end